Repository Nishune/Kino_Group_Project, pull requests merged in 2024-12, with the labels that each got.

#64 Movies html
  README.md
  data/movies.json
  data/moviesHeadline.json
  index.html
  pages/img/Movieimg.png
  pages/index/movies.js
Labels: Filmer

#76 Filmer fetch api
  data/moviesHeadline.json
  index.html
  pages/about/about.html
  pages/index/movies.js
  pages/kids/kids.html
Labels: Filmer

#90 Fix bug where code was deleted and path to footer.js in about.html
  data/infoModal.json
  pages/about/about.html
  pages/img/QnAClose.png
  pages/img/QnAOpen.png
  pages/img/kinoImg.png
  pages/index/infoModal.js
Labels: Bug

#95 Filmer mobile and desktop style
  data/movies.json
  pages/img/Movieimg.png
  pages/index/movies.js
  pages/index/movies.scss
  style.scss
Labels: Filmer

#97 Info modal mobile style
  pages/index/index.scss
  pages/index/infoModal.js
  pages/index/infoModal.scss
  style.scss
Labels: Informationsmodal
